# Generated by Django 3.1.6 on 2021-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='team_pic/y%/m%/d%')),
                ('facebook_url', models.URLField()),
                ('twitter', models.URLField()),
                ('google_plus_url', models.URLField()),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
