# Generated by Django 3.1.6 on 2021-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzone_page_app', '0002_auto_20210218_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='photo',
            field=models.ImageField(upload_to='team_pic/'),
        ),
    ]
