# Generated by Django 3.1.6 on 2021-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Fuel_Type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='passenger',
            field=models.IntegerField(),
        ),
    ]
